*** Variables ***
${BOOKING_HOTEL_ID_INPUT}       id=bookingHotelId
${BOOKING_CUSTOMER_INPUT}       id=customerName
${BOOKING_PEOPLE_INPUT}         id=people
${BOOKING_BEDS_INPUT}           id=beds
${BOOKING_TWIN_BEDS_INPUT}      id=twinBeds
${BOOKING_CHECK_IN_INPUT}       id=checkInDate
${BOOKING_CHECK_OUT_INPUT}      id=checkOutDate

${BOOKING_SUBMIT_BTN}           xpath=//button[contains(text(), 'Book Room')]

${BOOKING_OUTPUT}               id=bookingOutput
${BOOKING_TOAST}                id=toast
